---
openapi: 3.0.0
info:
  title: "Shopping Cart"
  description: "API for general usage shopping cart"
  version: "1.0.0"
components:
  securitySchemes:
    BasucAuth:
      type: http
      scheme: basic